#
#
# Copyright 2016 The Symphony Software Foundation
#
# Licensed to The Symphony Software Foundation (SSF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

language: java

before_install:
  - "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash"
  - "nvm install 6.10"
  - "nvm use 6.10"
  - "npm update -g npm"

install: true

jdk:
  - oraclejdk8

env:
  global:
    - secure: "UMp5p2KqKrdtYGLW7xA4P5Rh+GzSIZa90sJUDhB/+o0oDhCev7fGhW4btpEFccmty8sfNgtPWFPRthkgRhmJeqGkXGmEAXoZVsTsZQC62YbT6+4zpqrthOwcI8+jUJj59z3sJlrnOM18v863V/8bt5if+9upNTdPU+eqpAmAt45WB98FEkMV2I6zN4eBAd3us2XmCgZuSH/lOMx10GP2J1RWSVICNkwhdJ6jxqwVHpbgXoxSZe5o70ckvxRE4678RHf/1MR4O5RoVPkg7xRdlEF7CV7AFt9bmvxZi7W8aKs4TkqDkqVBzKaDc6z1vjTijI048H1OU8xGAcPAnwtmVVE1XTxu5kl/xkaeqaEb5Ga0vsBYP4KxfS7FYHdSfelrTiwxozPVrXme1do1W0fgxAHGHDzGIK50IuC6bqY4E/KK8Y0sMxesQnJdKtpSTFEBE9s5QDvpuNXYmrJOj++8oeRj2RQz3iZKN1WvFydQL4ZauPC4BI6rIQRAKqxN0sW7OGWXhm5Q1CKwE1vnwpumlO/2x+9P4bQ0NfhSmCAMZzU89ZQvTg2g03ITIJyVw879bdvGOflu+LP0jZ4rd5FuOnvYT1w/cu/rKy4cvgD6hTbi7V+reLyt7fGbS5qIfmOOTVCejCcyhwXp+0vEY+VTC/+HqLm4xmdxpredKT9/MP0="

addons:
  coverity_scan:
    project:
      name: "symphonyoss/App-Integrations-Trello"
      description: "Build submitted via Travis CI"
    notification_email: "integrations-team@symphony.com"
    build_command_prepend: "mvn clean"
    build_command:   "mvn -Denv=dev -DsymphonySkipUnitTests=true install"
    branch_pattern: "dev"

before_script:
  - npm install -g gulp

script:
- "if [[ \"$TRAVIS_PULL_REQUEST\" = \"false\" && $TRAVIS_BRANCH =~ dev ]]; then mvn clean deploy -Pversioneye,whitesource -Pcobertura -DtransitiveDependencies=true --settings settings.xml ; fi"
- "if [[ \"$TRAVIS_PULL_REQUEST\" != \"false\" ]]; then mvn clean package -Pcobertura; fi"

- npm install
# Cannot run on external PRs due to https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
- "if [[ $TRAVIS_PULL_REQUEST -eq 'false' ]]; then npm run whitesource; fi;"
# Break the build, if any Whitesource policy violation is found
- "if [[ -e 'ws-log-policy-violations.json' ]]; then echo 'Found Whitesource Policy violation, build failed.' ; exit -1; fi;"

after_success:
- bash <(curl -s https://codecov.io/bash)